name: E2E Test

on:
  pull_request:
    branches:
      - main

jobs:
  test-lambda-mono:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Setup Node.js
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3
        with:
          node-version: 18

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: true

      - name: Install playwright browsers
        run: pnpx playwright install

      - name: Test
        run: pnpm test
        env:
          ADAPTER_FQDN: lambda-mono.adapter-aws.com

  # test-lambda-s3:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: 18
  #     - uses: pnpm/action-setup@v2
  #       with:
  #         version: latest
  #         run_install: true
  #     - run: pnpx playwright install
  #     - run: pnpm test
  #       env:
  #         PREVIEW_URL: ${{secrets.LAMBDA_S3_PREVIEW_URL}}

  # test-edge-bundled:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: 18
  #     - uses: pnpm/action-setup@v2
  #       with:
  #         version: latest
  #         run_install: true
  #     - run: pnpx playwright install
  #     - run: pnpm test
  #       env:
  #         PREVIEW_URL: ${{secrets.EDGE_BUNDLED_PREVIEW_URL}}

  # test-edge-unbundled:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: 18
  #     - uses: pnpm/action-setup@v2
  #       with:
  #         version: latest
  #         run_install: true
  #     - run: pnpx playwright install
  #     - run: pnpm test
  #       env:
  #         PREVIEW_URL: ${{secrets.EDGE_UNBUNDLED_PREVIEW_URL}}
